[2023-07-02T21:25:34.892+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T15:45:54.142264+00:00 [queued]>
[2023-07-02T21:25:34.899+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T15:45:54.142264+00:00 [queued]>
[2023-07-02T21:25:34.899+0530] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-02T21:25:34.910+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_etl> on 2023-07-02 15:45:54.142264+00:00
[2023-07-02T21:25:34.916+0530] {standard_task_runner.py:57} INFO - Started process 97218 to run task
[2023-07-02T21:25:34.921+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_dag', 'run_etl', 'manual__2023-07-02T15:45:54.142264+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/tmpb0c35bmf']
[2023-07-02T21:25:34.924+0530] {standard_task_runner.py:85} INFO - Job 14: Subtask run_etl
[2023-07-02T21:25:34.967+0530] {task_command.py:410} INFO - Running <TaskInstance: load_data_dag.run_etl manual__2023-07-02T15:45:54.142264+00:00 [running]> on host shubhams-macbook-air.local
[2023-07-02T21:25:35.012+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_data_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T15:45:54.142264+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T15:45:54.142264+00:00'
[2023-07-02T21:25:35.014+0530] {load_data_dag.py:26} INFO - About to call endpoint http://localhost:8000/load-data
[2023-07-02T21:26:00.143+0530] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-07-02T21:26:00.154+0530] {process_utils.py:131} INFO - Sending 15 to group 97218. PIDs of all processes in the group: [97218]
[2023-07-02T21:26:00.155+0530] {process_utils.py:86} INFO - Sending the signal 15 to group 97218
[2023-07-02T21:27:00.188+0530] {process_utils.py:149} WARNING - process psutil.Process(pid=97218, name='Python', status='running', started='21:25:34') did not respond to SIGTERM. Trying SIGKILL
[2023-07-02T21:27:00.193+0530] {process_utils.py:86} INFO - Sending the signal 9 to group 97218
[2023-07-02T21:27:00.201+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=97218, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='21:25:34') (97218) terminated with exit code -9
[2023-07-02T21:27:00.202+0530] {standard_task_runner.py:172} ERROR - Job 14 was killed before it finished (likely due to running out of memory)
