[2023-07-02T22:03:43.715+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:15:53.761785+00:00 [queued]>
[2023-07-02T22:03:43.725+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:15:53.761785+00:00 [queued]>
[2023-07-02T22:03:43.725+0530] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-02T22:03:43.746+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_etl> on 2023-07-02 16:15:53.761785+00:00
[2023-07-02T22:03:43.753+0530] {standard_task_runner.py:57} INFO - Started process 591 to run task
[2023-07-02T22:03:43.777+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_dag', 'run_etl', 'manual__2023-07-02T16:15:53.761785+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/tmpxxconv0g']
[2023-07-02T22:03:43.781+0530] {standard_task_runner.py:85} INFO - Job 33: Subtask run_etl
[2023-07-02T22:03:43.853+0530] {task_command.py:410} INFO - Running <TaskInstance: load_data_dag.run_etl manual__2023-07-02T16:15:53.761785+00:00 [running]> on host shubhams-macbook-air.local
[2023-07-02T22:03:43.937+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='load_data_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T16:15:53.761785+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T16:15:53.761785+00:00'
[2023-07-02T22:03:43.942+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T
[2023-07-02T22:03:43.944+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -x GET http://localhost:8000/load-data']
[2023-07-02T22:03:43.952+0530] {subprocess.py:86} INFO - Output:
[2023-07-02T22:03:44.038+0530] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-07-02T22:03:44.042+0530] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-07-02T22:03:44.069+0530] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (5) Could not resolve proxy: GET
[2023-07-02T22:03:44.070+0530] {subprocess.py:97} INFO - Command exited with return code 5
[2023-07-02T22:03:44.083+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shubhampriyadarshi/PycharmProjects/PacktAPI/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2023-07-02T22:03:44.087+0530] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=load_data_dag, task_id=run_etl, execution_date=20230702T161553, start_date=20230702T163343, end_date=20230702T163344
[2023-07-02T22:03:44.097+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task run_etl (Bash command failed. The command returned a non-zero exit code 5.; 591)
[2023-07-02T22:03:44.141+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T22:03:44.162+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
